In [2]:
print("hii")

hii


connect to drive

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


import library bold text

In [4]:
import pandas as pd
import numpy as np

dataset

In [8]:
df=pd.read_csv("/content/drive/MyDrive/Colab Notebooks/spam.csv",encoding="ISO-8859-1")

In [9]:
df.head()

v1                                                 v2 Unnamed: 2  \
0   ham  Go until jurong point, crazy.. Available only ...        NaN   
1   ham                      Ok lar... Joking wif u oni...        NaN   
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3   ham  U dun say so early hor... U c already then say...        NaN   
4   ham  Nah I don't think he goes to usf, he lives aro...        NaN   

  Unnamed: 3 Unnamed: 4  
0        NaN        NaN  
1        NaN        NaN  
2        NaN        NaN  
3        NaN        NaN  
4        NaN        NaN

In [14]:
df.describe

<bound method NDFrame.describe of         v1                                                 v2 Unnamed: 2  \
0      ham  Go until jurong point, crazy.. Available only ...        NaN   
1      ham                      Ok lar... Joking wif u oni...        NaN   
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3      ham  U dun say so early hor... U c already then say...        NaN   
4      ham  Nah I don't think he goes to usf, he lives aro...        NaN   
...    ...                                                ...        ...   
5567  spam  This is the 2nd time we have tried 2 contact u...        NaN   
5568   ham              Will Ì_ b going to esplanade fr home?        NaN   
5569   ham  Pity, * was in mood for that. So...any other s...        NaN   
5570   ham  The guy did some bitching but I acted like i'd...        NaN   
5571   ham                         Rofl. Its true to its name        NaN   

     Unnamed: 3 Unnamed: 4  
0           NaN        N

In [16]:
df['spam'] = df['v1'].apply(lambda x: 1 if x =='spam' else 0)

In [17]:
df.shape

(5572, 6)

In [18]:
df.head()

v1                                                 v2 Unnamed: 2  \
0   ham  Go until jurong point, crazy.. Available only ...        NaN   
1   ham                      Ok lar... Joking wif u oni...        NaN   
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3   ham  U dun say so early hor... U c already then say...        NaN   
4   ham  Nah I don't think he goes to usf, he lives aro...        NaN   

  Unnamed: 3 Unnamed: 4  spam  
0        NaN        NaN     0  
1        NaN        NaN     0  
2        NaN        NaN     1  
3        NaN        NaN     0  
4        NaN        NaN     0

In [19]:
df.columns

Index(['v1', 'v2', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'spam'], dtype='object')

In [25]:
df=df.drop(['Unnamed: 2','Unnamed: 3','Unnamed: 4'],axis="columns")

In [26]:
df

v1                                                 v2  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0
...    ...                                                ...   ...
5567  spam  This is the 2nd time we have tried 2 contact u...     1
5568   ham              Will Ì_ b going to esplanade fr home?     0
5569   ham  Pity, * was in mood for that. So...any other s...     0
5570   ham  The guy did some bitching but I acted like i'd...     0
5571   ham                         Rofl. Its true to its name     0

[5572 rows x 3 columns]

In [27]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df.v2, df.spam, test_size=0.2)

In [28]:
X_train.shape

(4457,)

In [29]:
X_test.shape

(1115,)

bag of word

In [30]:
from sklearn.feature_extraction.text import CountVectorizer

v = CountVectorizer()

X_train_cv = v.fit_transform(X_train.values)
X_train_cv

<4457x7776 sparse matrix of type '<class 'numpy.int64'>'
	with 59432 stored elements in Compressed Sparse Row format>

In [31]:
X_train_cv.toarray()[:2][0]

array([0, 0, 0, ..., 0, 0, 0])

In [32]:
X_train_cv.shape

(4457, 7776)

In [33]:
v.get_feature_names_out()[1771]

'checking'

In [34]:
v.vocabulary_

{'will': 7534,
 'do': 2401,
 'have': 3386,
 'good': 3212,
 'day': 2204,
 'never': 4780,
 'blame': 1383,
 'in': 3669,
 'ur': 7216,
 'life': 4123,
 'days': 2205,
 'give': 3177,
 'happiness': 3363,
 'bad': 1197,
 'experience': 2752,
 'both': 1450,
 'are': 1041,
 'essential': 2678,
 'all': 897,
 'gods': 3196,
 'blessings': 1393,
 'morning': 4617,
 'just': 3901,
 'wait': 7369,
 'till': 6913,
 'end': 2612,
 'of': 4915,
 'march': 4381,
 'when': 7497,
 'el': 2578,
 'nino': 4812,
 'gets': 3155,
 'himself': 3461,
 'oh': 4935,
 'll': 4182,
 'text': 6804,
 'carlos': 1676,
 'and': 946,
 'let': 4107,
 'you': 7722,
 'know': 3984,
 'hang': 3348,
 'on': 4959,
 'well': 7469,
 'done': 2437,
 'your': 7728,
 'costa': 2043,
 'del': 2252,
 'sol': 6302,
 'holiday': 3495,
 'or': 4999,
 '5000': 526,
 'await': 1162,
 'collection': 1913,
 'call': 1615,
 '09050090044': 172,
 'now': 4867,
 'toclaim': 6953,
 'sae': 5891,
 'tcs': 6746,
 'pobox334': 5295,
 'stockport': 6506,
 'sk38xh': 6214,
 'costå': 2047,
 '50': 524

In [35]:
X_train_np = X_train_cv.toarray()
X_train_np[0]

array([0, 0, 0, ..., 0, 0, 0])

In [36]:
np.where(X_train_np[0]!=0)

(array([2204, 2401, 3212, 3386, 7534]),)

model 

In [38]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(X_train_cv, y_train)

MultinomialNB()

In [39]:
X_test_cv = v.transform(X_test)

In [40]:
from sklearn.metrics import classification_report

y_pred = model.predict(X_test_cv)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       980
           1       0.98      0.90      0.94       135

    accuracy                           0.99      1115
   macro avg       0.99      0.95      0.97      1115
weighted avg       0.99      0.99      0.99      1115



result

In [41]:
emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]

emails_count = v.transform(emails)
model.predict(emails_count)

array([0, 1])

In [45]:
msg=[ "Dear Sneh SinghThe more you repeat it, the better you’ll be at it. This expression is true for Job Interviews. Practice our well-crafted mock interviews created by top industry experts before heading toward cracking the final interview Benefits of Mock Interview:Boost your confidence by practicing for interviewsFaster employmentAssist you in getting ready for behaviorally-based interview questionsReduce the stress and anxiety of applicants before a real job interviewGet interviewed by the industry experts, pertaining to your profile @Rs. 2200 only."]

In [46]:
msg_c=v.transform(msg)

In [47]:
model.predict(msg_c)

array([0])

In [51]:
m=["Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!"]

In [52]:
mc=v.transform(m)

In [53]:
model.predict(mc)

array([1])